author: mirrord.dev
repoHost: GitHub
docsRepo: 'https://github.com/metalbear-co/mirrord.dev'
docsRepoBranch: master
docsRepoSubPath: ''
title: mirrord
titleSeparator: '-'
titleAddition: Rethinking cloud development
description: >-
  mirrord is a cli/IDE extension that lets backend developers run their local
  code in the context of the remote environment.
images:
  - logo.jpg
ogLocale: en_US
domainTLD: mirrord.dev
titleHome: mirrord
twitterSite: '@metalbearco'
twitterCreator: '@metalbearco'
schemaType: Organization
schemaName: mirrord
schemaAuthor: MetalBear
schemaAuthorTwitter: 'https://twitter.com/metalbearco'
schemaAuthorLinkedIn: 'https://www.linkedin.com/company/metalbearco/'
schemaAuthorGitHub: 'https://github.com/metalbear-co'
schemaLocale: en-US
schemaLogo: logo.jpg
schemaLogoWidth: 512
schemaLogoHeight: 512
schemaImage: logo.jpg
schemaImageWidth: 1280
schemaImageHeight: 640
schemaTwitter: 'https://twitter.com/metalbearco'
schemaLinkedIn: 'https://www.linkedin.com/company/metalbearco/'
schemaGitHub: 'https://github.com/metalbear-co/mirrord'
schemaSection: blog

alert: true
alertDismissable: true
alertText: "🪞 mirrord for Teams is out now! Get started <a class=\"alert-link stretched-link\" href=\"/docs/teams/introduction\" rel=\"noopener\">here</a>."